baseURL = 'https://Diing54.github.io/devops/'
title = "Diing"
theme = ["github.com/imfing/hextra"]

[params]
  description = "My Kasten"
  # Hextra checks 'assets/' by default
  customCSS = ["css/custom.css"]

[markup.goldmark.renderer]
  unsafe = true
