baseURL = 'https://Diing54.github.io/devops/'
title = "Diing's Tech Yard"
theme = ["github.com/imfing/hextra"]

[params]
  description = "DevOps Engine Room"
  # This array ensures our CSS overrides the theme defaults
  customCSS = ["css/custom.css"]

[markup.goldmark.renderer]
  unsafe = true
