baseURL = 'https://Diing54.github.io/devops/'
languageCode = 'en-us'
title = 'DevOps Brain'
theme = "github.com/imfing/hextra"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Notes"
    url = "/docs/"
    weight = 1

[params]
  navbar = true
  footer = false 

  [params.search]
    enable = true
    type = "flexsearch"

  [params.editURL]
    enable = false
